### ISSUE TITLE
Equivalent of static selector

### ISSUE THREAD

**Issue by pipe01** [asim/nitro-plugins#605]
Previously, when using Go Micro I had this:

```go
svc.Init(micro.Selector(static.NewSelector()))
```

But now it seems that selectors aren't a thing anymore. Is it static now by default?

**Comment by asim** [comment]
See router package.

**Comment by pipe01** [comment]
I tried doing
```go
svc.Server().Init(server.WithRouter(static.NewRouter()))
```

But it says `cannot use static.NewRouter() (value of type router.Router) as server.Router value in argument to server.WithRouter`, where should I put it?

**Comment by asim** [comment]
It goes in the client not the server. The client does the routing.

**Comment by pipe01** [comment]
Ah I see, that makes sense. Thanks a lot!
